("https://www.logicmatters.net/feed/"
 "https://bartoszmilewski.com/feed"
 "https://joeyh.name/blog/index.rss"
 "https://protesilaos.com/master.xml"
 "https://jakob.space/feed.xml"
 "https://taylor.town/feed.xml"
 "https://flak.tedunangst.com/rss"
 "https://jvns.ca/atom.xml"
 "https://www.ralfj.de/blog/feed.xml"
 "https://www.boristhebrave.com/feed/"
 "https://iczelia.net/index.xml"
 "https://peetseater.space/blag/feed.xml"
 "https://curiouscoding.nl/index.xml"
 "https://faultlore.com/blah/rss.xml"
 "https://thephd.dev/feed.xml"
 "https://kibty.town/blog.rss"
 "https://blog.ganets.ky/feed"
 "https://cadence.moe/blog/atom.xml?limit=30"
 "https://devblogs.microsoft.com/oldnewthing/feed/"
 "https://nibblestew.blogspot.com/feeds/posts/default"
 "https://herbsutter.com/feed"
 "https://matklad.github.io/feed.xml"

 ("https://nullprogram.com/feed/" emacs)
 ("https://xenodium.com/feed" emacs)
 ("https://olddeuteronomy.github.io/index.xml" emacs)
 ("https://irreal.org/blog/?feed=rss2" emacs)

 ("http://blog.sigfpe.com/feeds/posts/default" math)
 ("blog.evanchen.cc/feed" math)
 ("https://golem.ph.utexas.edu/category/atom10.xml" math)

 ("https://bernsteinbear.com/feed.xml" compiler)
 ("https://cybercat.institute/feed.xml" fp)
 ("https://www.haskellforall.com/feeds/posts/default" fp)
 ("https://feeds.feedburner.com/incodeblog" fp)
 ("https://www.well-typed.com/blog/rss2.xml" fp)
 ("https://thomasjm.github.io/feed.xml" fp)
 ("https://blog.poisson.chat/rss.xml" fp)
 ("https://chrispenner.ca/atom.xml" fp)
 ("https://quuxplusone.github.io/blog/feed" cpp)

 ("https://www.todepond.com/feed/index.xml" cg)
 ("https://jendrikillner.com/tags/weekly/index.xml" cg)
 ("https://blog.frost.kiwi/feed.xml" cg)
 ("https://30fps.net/atom.xml" cg)

 ("https://people.kernel.org/read/feed/" os)
 ("https://os.phil-opp.com/rss.xml" os)
 ("https://archlinux.org/feeds/news/" arch)

 ("https://chipsandcheese.com/feed" hw)
 ("https://www.copetti.org/index.xml" hw))
