("https://www.logicmatters.net/feed/"
 "https://joeyh.name/blog/index.rss"
 "https://protesilaos.com/codelog.xml" "https://jakob.space/feed.xml"
 "https://taylor.town/feed.xml" "https://flak.tedunangst.com/rss"
 "https://jvns.ca/atom.xml" "https://www.ralfj.de/blog/feed.xml"
 "https://www.boristhebrave.com/feed/" "https://iczelia.net/index.xml"
 "https://peetseater.space/blag/feed.xml"
 "https://curiouscoding.nl/index.xml"
 "https://faultlore.com/blah/rss.xml" "https://thephd.dev/feed.xml"
 "https://kibty.town/blog.rss"

 ("https://nullprogram.com/feed/" emacs)
 ("https://xenodium.com/feed" emacs)
 ("https://olddeuteronomy.github.io/index.xml" emacs)
 ("https://irreal.org/blog/?feed=rss2" emacs)

 ("http://blog.sigfpe.com/feeds/posts/default" math)
 ("blog.evanchen.cc/feed" math)
 ("https://golem.ph.utexas.edu/category/atom10.xml" math)

 ("https://bernsteinbear.com/feed.xml" compiler)
 ("https://cybercat.institute/feed.xml" fp)
 ("https://feeds.feedburner.com/incodeblog" fp)

 ("https://www.todepond.com/feed/index.xml" cg)
 ("https://jendrikillner.com/tags/weekly/index.xml" cg)
 ("https://blog.frost.kiwi/feed.xml" cg)
 ("https://30fps.net/atom.xml" cg)

 ("https://people.kernel.org/read/feed/" os)
 ("https://os.phil-opp.com/rss.xml" os)

 ("https://www.cnx-software.com/feed" hw)
 ("https://chipsandcheese.com/feed" hw)
 ("https://www.copetti.org/index.xml" hw))
